export interface VerbEntry {
  id: string;
  spanish: string;
  armenian: string;
  type: 'ar' | 'er' | 'ir' | 'reflexive' | 'phrase';
  baseVerb: string; // Single infinitive form for conjugation game if applicable
  notes?: string;
}

export const VERBS_DATA: VerbEntry[] = [
  { id: "1", spanish: "aceptar", armenian: "ընդունել", type: "ar", baseVerb: "aceptar" },
  { id: "2", spanish: "acoger", armenian: "ընդունել / հյուրընկալել", type: "er", baseVerb: "acoger" },
  { id: "3", spanish: "acabar", armenian: "ավարտել", type: "ar", baseVerb: "acabar" },
  { id: "4", spanish: "comprar", armenian: "գնել", type: "ar", baseVerb: "comprar" },
  { id: "5", spanish: "encantar", armenian: "շատ դուր գալ", type: "ar", baseVerb: "encantar" },
  { id: "6", spanish: "ayudar", armenian: "օգնել", type: "ar", baseVerb: "ayudar" },
  { id: "7", spanish: "gustar", armenian: "դուր գալ", type: "ar", baseVerb: "gustar" },
  { id: "8", spanish: "querer", armenian: "ուզել / սիրել", type: "er", baseVerb: "querer" },
  { id: "9", spanish: "añadir", armenian: "ավելացնել", type: "ir", baseVerb: "añadir" },
  { id: "10", spanish: "ir", armenian: "գնալ", type: "ir", baseVerb: "ir" },
  { id: "11", spanish: "ir a clase", armenian: "դասի գնալ", type: "phrase", baseVerb: "ir" },
  { id: "12", spanish: "ir bien / mal", armenian: "լավ / վատ ստացվել", type: "phrase", baseVerb: "ir" },
  { id: "13", spanish: "recoger", armenian: "վերցնել / գնալ վերցնելու", type: "er", baseVerb: "recoger" },
  { id: "14", spanish: "irse de fiesta", armenian: "երեկույթի գնալ", type: "phrase", baseVerb: "irse" },
  { id: "15", spanish: "ir de compras", armenian: "գնումների գնալ", type: "phrase", baseVerb: "ir" },
  { id: "16", spanish: "ir de tiendas", armenian: "խանութներով շրջել", type: "phrase", baseVerb: "ir" },
  { id: "17", spanish: "ir de copas", armenian: "խմելու գնալ", type: "phrase", baseVerb: "ir" },
  { id: "18", spanish: "ir a tomar algo", armenian: "ինչ-որ բան խմելու / ուտելու գնալ", type: "phrase", baseVerb: "ir" },
  { id: "19", spanish: "irse de vacaciones", armenian: "արձակուրդ գնալ", type: "phrase", baseVerb: "irse" },
  { id: "20", spanish: "irse de viaje", armenian: "ճանապարհորդության գնալ", type: "phrase", baseVerb: "irse" },
  { id: "21", spanish: "encender", armenian: "վառել / միացնել", type: "er", baseVerb: "encender" },
  { id: "22", spanish: "traer", armenian: "բերել", type: "er", baseVerb: "traer" },
  { id: "23", spanish: "llevar", armenian: "տանել / կրել", type: "ar", baseVerb: "llevar" },
  { id: "24", spanish: "cancelar", armenian: "չեղարկել", type: "ar", baseVerb: "cancelar" },
  { id: "25", spanish: "llamar", armenian: "զանգել / կանչել", type: "ar", baseVerb: "llamar" },
  { id: "26", spanish: "aprender", armenian: "սովորել", type: "er", baseVerb: "aprender" },
  { id: "27", spanish: "enseñar", armenian: "սովորեցնել", type: "ar", baseVerb: "enseñar" },
  { id: "28", spanish: "arreglar", armenian: "կարգավորել / վերանորոգել", type: "ar", baseVerb: "arreglar" },
  { id: "29", spanish: "parar", armenian: "կանգնել / դադարեցնել", type: "ar", baseVerb: "parar" },
  { id: "30", spanish: "dejar de + infinitivo", armenian: "դադարել ինչ-որ բան անել", type: "phrase", baseVerb: "dejar" },
  { id: "31", spanish: "llegar", armenian: "հասնել", type: "ar", baseVerb: "llegar" },
  { id: "32", spanish: "conseguir", armenian: "կարողանալ / հասնել արդյունքի", type: "ir", baseVerb: "conseguir" },
  { id: "33", spanish: "esperar", armenian: "սպասել / հուսալ", type: "ar", baseVerb: "esperar" },
  { id: "34", spanish: "atraer", armenian: "գրավել", type: "er", baseVerb: "atraer" },
  { id: "35", spanish: "llamar la atención", armenian: "ուշադրություն գրավել", type: "phrase", baseVerb: "llamar" },
  { id: "36", spanish: "aumentar", armenian: "մեծացնել / ավելանալ", type: "ar", baseVerb: "aumentar" },
  { id: "37", spanish: "tener", armenian: "ունենալ", type: "er", baseVerb: "tener" },
  { id: "38", spanish: "haber", armenian: "լինել / ունենալ որպես օժանդակ բայ", type: "er", baseVerb: "haber" },
  { id: "39", spanish: "necesitar", armenian: "կարիք ունենալ", type: "ar", baseVerb: "necesitar" },
  { id: "40", spanish: "confiar en", armenian: "վստահել", type: "ar", baseVerb: "confiar" },
  { id: "41", spanish: "tener clase", armenian: "դաս ունենալ", type: "phrase", baseVerb: "tener" },
  { id: "42", spanish: "tener ganas de", armenian: "ցանկություն ունենալ", type: "phrase", baseVerb: "tener" },
  { id: "43", spanish: "tener pinta de", armenian: "տեսք ունենալ", type: "phrase", baseVerb: "tener" },
  { id: "44", spanish: "tenerlo claro", armenian: "հստակ հասկանալ", type: "phrase", baseVerb: "tener" },
  { id: "45", spanish: "soler", armenian: "սովորաբար անել", type: "er", baseVerb: "soler" },
  { id: "46", spanish: "doler", armenian: "ցավեցնել", type: "er", baseVerb: "doler" },
  { id: "47", spanish: "charlar", armenian: "զրուցել", type: "ar", baseVerb: "charlar" },
  { id: "48", spanish: "llevarse bien / mal con alguien", armenian: "ինչ-որ մեկի հետ լավ / վատ հարաբերություններ ունենալ", type: "phrase", baseVerb: "llevarse" },
  { id: "49", spanish: "beber", armenian: "խմել", type: "er", baseVerb: "beber" },
  { id: "50", spanish: "moverse", armenian: "շարժվել", type: "reflexive", baseVerb: "moverse" },
  { id: "51", spanish: "ponerse moreno", armenian: "արևահարվել / թխանալ", type: "phrase", baseVerb: "ponerse" },
  { id: "52", spanish: "calcular", armenian: "հաշվել", type: "ar", baseVerb: "calcular" },
  { id: "53", spanish: "cambiar", armenian: "փոխել", type: "ar", baseVerb: "cambiar" },
  { id: "54", spanish: "cantar", armenian: "երգել", type: "ar", baseVerb: "cantar" },
  { id: "55", spanish: "chatear", armenian: "չաթով գրել", type: "ar", baseVerb: "chatear" },
  { id: "56", spanish: "buscar", armenian: "փնտրել", type: "ar", baseVerb: "buscar" },
  { id: "57", spanish: "elegir", armenian: "ընտրել", type: "ir", baseVerb: "elegir" },
  { id: "58", spanish: "empezar", armenian: "սկսել", type: "ar", baseVerb: "empezar" },
  { id: "59", spanish: "comentar", armenian: "մեկնաբանել", type: "ar", baseVerb: "comentar" },
  { id: "60", spanish: "completar", armenian: "լրացնել", type: "ar", baseVerb: "completar" },
  { id: "61", spanish: "entender", armenian: "հասկանալ", type: "er", baseVerb: "entender" },
  { id: "62", spanish: "contar con", armenian: "հույս դնել / հաշվի առնել", type: "phrase", baseVerb: "contar" },
  { id: "63", spanish: "conducir", armenian: "վարել", type: "ir", baseVerb: "conducir" },
  { id: "64", spanish: "conocer", armenian: "ճանաչել / ծանոթ լինել", type: "er", baseVerb: "conocer" },
  { id: "65", spanish: "conectar", armenian: "მიացնել / կապել", type: "ar", baseVerb: "conectar" },
  { id: "66", spanish: "aconsejar", armenian: "խորհուրդ տալ", type: "ar", baseVerb: "aconsejar" },
  { id: "67", spanish: "consultar", armenian: "խորհրդակցել / նայել", type: "ar", baseVerb: "consultar" },
  { id: "68", spanish: "seguir recto", armenian: "ուղիղ շարունակել", type: "phrase", baseVerb: "seguir" },
  { id: "69", spanish: "seguir + gerundio", armenian: "շարունակել անել", type: "phrase", baseVerb: "seguir" },
  { id: "70", spanish: "corregir", armenian: "ուղղել", type: "ir", baseVerb: "corregir" },
  { id: "71", spanish: "correr", armenian: "վազել", type: "er", baseVerb: "correr" },
  { id: "72", spanish: "costar", armenian: "արժենալ / դժվար լինել", type: "ar", baseVerb: "costar" },
  { id: "73", spanish: "crear", armenian: "ստեղծել", type: "ar", baseVerb: "crear" },
  { id: "74", spanish: "creer", armenian: "հավատալ / կարծել", type: "er", baseVerb: "creer" },
  { id: "75", spanish: "cocinar", armenian: "պատրաստել / եփել", type: "ar", baseVerb: "cocinar" },
  { id: "76", spanish: "decidir", armenian: "որոշել", type: "ir", baseVerb: "decidir" },
  { id: "77", spanish: "desconectar", armenian: "անջատել", type: "ar", baseVerb: "desconectar" },
  { id: "78", spanish: "descubrir", armenian: "բացահայտել", type: "ir", baseVerb: "descubrir" },
  { id: "79", spanish: "comer", armenian: "ուտել", type: "er", baseVerb: "comer" },
  { id: "80", spanish: "pedir", armenian: "խնդրել / պատվիրել", type: "ir", baseVerb: "pedir" },
  { id: "81", spanish: "pedir permission", armenian: "թույլտվություն խնդրել", type: "phrase", baseVerb: "pedir" },
  { id: "82", spanish: "preguntar", armenian: "հարցնել", type: "ar", baseVerb: "preguntar" },
  { id: "83", spanish: "depender", armenian: "կախված լինել", type: "er", baseVerb: "depender" },
  { id: "84", spanish: "gastar", armenian: "ծախսել", type: "ar", baseVerb: "gastar" },
  { id: "85", spanish: "molestar", armenian: "անհանգստացնել", type: "ar", baseVerb: "molestar" },
  { id: "86", spanish: "bajar", armenian: "իջնել / ներբեռնել", type: "ar", baseVerb: "bajar" },
  { id: "87", spanish: "dibujar", armenian: "նկարել", type: "ar", baseVerb: "dibujar" },
  { id: "88", spanish: "desarrollar", armenian: "զարգացնել", type: "ar", baseVerb: "desarrollar" },
  { id: "89", spanish: "volverse", armenian: "դառնալ", type: "reflexive", baseVerb: "volverse" },
  { id: "90", spanish: "tener que", armenian: "պետք է անել", type: "phrase", baseVerb: "tener" },
  { id: "91", spanish: "cenar", armenian: "ընթրել", type: "ar", baseVerb: "cenar" },
  { id: "92", spanish: "decir", armenian: "ասել", type: "ir", baseVerb: "decir" },
  { id: "93", spanish: "dar", armenian: "տալ", type: "ar", baseVerb: "dar" },
  { id: "94", spanish: "dar clase", armenian: "դաս տալ", type: "phrase", baseVerb: "dar" },
  { id: "95", spanish: "quedar con alguien", armenian: "պայմանավորվել / հանդիպել ինչ-որ մեկի հետ", type: "phrase", baseVerb: "quedar" },
  { id: "96", spanish: "echar una mano", armenian: "օգնության ձեռք մեկնել", type: "phrase", baseVerb: "echar" },
  { id: "97", spanish: "dormir", armenian: "քնել", type: "ir", baseVerb: "dormir" },
  { id: "98", spanish: "escribir", armenian: "գրել", type: "ir", baseVerb: "escribir" },
  { id: "99", spanish: "llevar a alguien", armenian: "ինչ-որ մեկին տանել", type: "phrase", baseVerb: "llevar" },
  { id: "100", spanish: "llevarse", armenian: "հետը տանել", type: "reflexive", baseVerb: "llevarse" },
  { id: "101", spanish: "estar harto/a de", armenian: "ձանձրացած / հոգնած լինել ինչ-որ բանից", type: "phrase", baseVerb: "estar" },
  { id: "102", spanish: "cobrar", armenian: "գումար ստանալ / գանձել", type: "ar", baseVerb: "cobrar" },
  { id: "103", spanish: "quitar", armenian: "հանել / հեռացնել", type: "ar", baseVerb: "quitar" },
  { id: "104", spanish: "grabar", armenian: "ձայնագրել / տեսագրել", type: "ar", baseVerb: "grabar" },
  { id: "105", spanish: "facturar el equipaje", armenian: "ուղեբեռը հանձնել", type: "phrase", baseVerb: "facturar" },
  { id: "106", spanish: "oír", armenian: "լսել", type: "ir", baseVerb: "oír" },
  { id: "107", spanish: "entrenarse", armenian: "մարզվել", type: "reflexive", baseVerb: "entrenarse" },
  { id: "108", spanish: "mandar", armenian: "ուղարկել", type: "ar", baseVerb: "mandar" },
  { id: "109", spanish: "probarse", armenian: "փորձել հագուստը", type: "reflexive", baseVerb: "probarse" },
  { id: "110", spanish: "intentar", armenian: "փորձել", type: "ar", baseVerb: "intentar" },
  { id: "111", spanish: "establecer", armenian: "հաստատել / սահմանել", type: "er", baseVerb: "establecer" },
  { id: "112", spanish: "apagar", armenian: "անջատել", type: "ar", baseVerb: "apagar" },
  { id: "113", spanish: "ser", armenian: "լինել", type: "er", baseVerb: "ser" },
  { id: "114", spanish: "estar", armenian: "լինել / գտնվել", type: "ar", baseVerb: "estar" },
  { id: "115", spanish: "ser de", armenian: "լինել ինչ-որ տեղից / պատկանել", type: "phrase", baseVerb: "ser" },
  { id: "116", spanish: "estar a gusto", armenian: "իրեն հարմար / լավ զգալ", type: "phrase", baseVerb: "estar" },
  { id: "117", spanish: "estar enamorado de", armenian: "սիրահարված լինել", type: "phrase", baseVerb: "estar" },
  { id: "118", spanish: "estar en paro", armenian: "գործազուրկ լինել", type: "phrase", baseVerb: "estar" },
  { id: "119", spanish: "estar bien", armenian: "լավ լինել", type: "phrase", baseVerb: "estar" },
  { id: "120", spanish: "estar moreno/a", armenian: "արևահարված / թխացած լինել", type: "phrase", baseVerb: "estar" },
  { id: "121", spanish: "estar de buen / mal humor", armenian: "լավ / վատ տրամադրություն ունենալ", type: "phrase", baseVerb: "estar" },
  { id: "122", spanish: "estar de paso", armenian: "անցողիկ / ժամանակավոր լինել", type: "phrase", baseVerb: "estar" },
  { id: "123", spanish: "estar divorciado", armenian: "ամուսնալուծված լինել", type: "phrase", baseVerb: "estar" },
  { id: "124", spanish: "dar igual", armenian: "միևնույն լինել", type: "phrase", baseVerb: "dar" },
  { id: "125", spanish: "estar en el instituto", armenian: "դպրոցում / ինստիտուտում սովորել", type: "phrase", baseVerb: "estar" },
  { id: "126", spanish: "estar de Erasmus", armenian: "Էրազմուս ծրագրով լինել", type: "phrase", baseVerb: "estar" },
  { id: "127", spanish: "estar de compras", armenian: "գնումներ անելիս լինել", type: "phrase", baseVerb: "estar" },
  { id: "128", spanish: "ser bueno / buena gente", armenian: "լավ մարդ լինել", type: "phrase", baseVerb: "ser" },
  { id: "129", spanish: "estar acostumbrado a", armenian: "սովոր լինել", type: "phrase", baseVerb: "estar" },
  { id: "130", spanish: "estar prohibido", armenian: "արգելված լինել", type: "phrase", baseVerb: "estar" },
  { id: "131", spanish: "estar malo", armenian: "հիվանդ լինել", type: "phrase", baseVerb: "estar" },
  { id: "132", spanish: "estar casado", armenian: "ամուսնացած լինել", type: "phrase", baseVerb: "estar" },
  { id: "133", spanish: "ser igual", armenian: "նույնը լինել", type: "phrase", baseVerb: "ser" },
  { id: "134", spanish: "tener prisa", armenian: "շտապել", type: "phrase", baseVerb: "tener" },
  { id: "135", spanish: "estar listo para", armenian: "պատրաստ լինել", type: "phrase", baseVerb: "estar" },
  { id: "136", spanish: "molar", armenian: "շատ դուր գալ / լավը լինել", type: "ar", baseVerb: "molar" },
  { id: "137", spanish: "explicar", armenian: "բացատրել", type: "ar", baseVerb: "explicar" },
  { id: "138", spanish: "facturar", armenian: "հաշիվ գրել / ուղեբեռ հանձնել", type: "ar", baseVerb: "facturar" },
  { id: "139", spanish: "hacer", armenian: "անել / պատրաստել", type: "er", baseVerb: "hacer" },
  { id: "140", spanish: "tener cuidado con", armenian: "զգույշ լինել", type: "phrase", baseVerb: "tener" },
  { id: "141", spanish: "hacer buen tiempo", armenian: "լավ եղանակ լինել", type: "phrase", baseVerb: "hacer" },
  { id: "142", spanish: "hacer calor", armenian: "շոգ լինել", type: "phrase", baseVerb: "hacer" },
  { id: "143", spanish: "hacer frío", armenian: "ցուրտ լինել", type: "phrase", baseVerb: "hacer" },
  { id: "144", spanish: "fregar los platos", armenian: "ամանները լվանալ", type: "phrase", baseVerb: "fregar" },
  { id: "145", spanish: "hacer daño", armenian: "ցավ պատճառել", type: "phrase", baseVerb: "hacer" },
  { id: "146", spanish: "dar miedo", armenian: "վախեցնել", type: "phrase", baseVerb: "dar" },
  { id: "147", spanish: "dar un paseo", armenian: "զբոսնել", type: "phrase", baseVerb: "dar" },
  { id: "148", spanish: "hacer unas prácticas", armenian: "պրակտիկա անցնել", type: "phrase", baseVerb: "hacer" },
  { id: "149", spanish: "dar una vuelta", armenian: "մի պտույտ անել / զբոսնել", type: "phrase", baseVerb: "dar" },
  { id: "150", spanish: "despedirse de", armenian: "հրաժեշտ տալ", type: "reflexive", baseVerb: "despedirse" },
  { id: "151", spanish: "cerrar", armenian: "փակել", type: "ar", baseVerb: "cerrar" },
  { id: "152", spanish: "celebrar", armenian: "տոնել", type: "ar", baseVerb: "celebrar" },
  { id: "153", spanish: "funcionar", armenian: "աշխատել / գործել", type: "ar", baseVerb: "funcionar" },
  { id: "154", spanish: "ganar", armenian: "հաղթել / վաստակել", type: "ar", baseVerb: "ganar" },
  { id: "155", spanish: "aparcar", armenian: "կայանել", type: "ar", baseVerb: "aparcar" },
  { id: "156", spanish: "merendar", armenian: "հետճաշիկ անել", type: "ar", baseVerb: "merendar" },
  { id: "157", spanish: "vivir", armenian: "ապրել", type: "ir", baseVerb: "vivir" },
  { id: "158", spanish: "dudar", armenian: "կասկածել / տատանվել", type: "ar", baseVerb: "dudar" },
  { id: "159", spanish: "hay que + infinitivo", armenian: "պետք է անել", type: "phrase", baseVerb: "haber" },
  { id: "160", spanish: "hace falta que", armenian: "անհրաժեշտ է, որ", type: "phrase", baseVerb: "hacer" },
  { id: "161", spanish: "faltar", armenian: "պակասել", type: "ar", baseVerb: "faltar" },
  { id: "162", spanish: "parecer", armenian: "թվալ", type: "er", baseVerb: "parecer" },
  { id: "163", spanish: "ocurrir", armenian: "պատահել / մտքով անցնել", type: "ir", baseVerb: "ocurrir" },
  { id: "164", spanish: "quedar", armenian: "մնալ", type: "ar", baseVerb: "quedar" },
  { id: "165", spanish: "imprimir", armenian: "տպել", type: "ir", baseVerb: "imprimir" },
  { id: "166", spanish: "indicar", armenian: "ցույց տալ / նշել", type: "ar", baseVerb: "indicar" },
  { id: "167", spanish: "prohibir", armenian: "արգելել", type: "ir", baseVerb: "prohibir" },
  { id: "168", spanish: "interesar", armenian: "հետաքրքրել", type: "ar", baseVerb: "interesar" },
  { id: "169", spanish: "invertir", armenian: "ներդնել", type: "ir", baseVerb: "invertir" },
  { id: "170", spanish: "invitar", armenian: "հրավիրել", type: "ar", baseVerb: "invitar" },
  { id: "171", spanish: "hacer falta", armenian: "պետք լինել / պակասել", type: "phrase", baseVerb: "hacer" },
  { id: "172", spanish: "tirar", armenian: "նետել", type: "ar", baseVerb: "tirar" },
  { id: "173", spanish: "echar", armenian: "գցել / նետել", type: "ar", baseVerb: "echar" },
  { id: "174", spanish: "jugar", armenian: "խաղալ", type: "ar", baseVerb: "jugar" },
  { id: "175", spanish: "tocar el piano / la guitarra", armenian: "դաշնամուր / կիթառ նվագել", type: "phrase", baseVerb: "tocar" },
  { id: "176", spanish: "dejar", armenian: "թողնել", type: "ar", baseVerb: "dejar" },
  { id: "177", spanish: "lavar", armenian: "լվանալ", type: "ar", baseVerb: "lavar" },
  { id: "178", spanish: "alquilar", armenian: "վարձել", type: "ar", baseVerb: "alquilar" },
  { id: "179", spanish: "echar de menos", armenian: "կարոտել", type: "phrase", baseVerb: "echar" },
  { id: "180", spanish: "andar", armenian: "քայլել", type: "ar", baseVerb: "andar" },
  { id: "181", spanish: "caminar", armenian: "քայլել", type: "ar", baseVerb: "caminar" },
  { id: "182", spanish: "merecer", armenian: "արժանի լինել", type: "er", baseVerb: "merecer" },
  { id: "183", spanish: "medir", armenian: "չափել", type: "ir", baseVerb: "medir" },
  { id: "184", spanish: "meter", armenian: "դնել ներս", type: "er", baseVerb: "meter" },
  { id: "185", spanish: "poner", armenian: "դնել", type: "er", baseVerb: "poner" },
  { id: "186", spanish: "subir", armenian: "բարձրանալ", type: "ir", baseVerb: "subir" },
  { id: "187", spanish: "montar a caballo", armenian: "ձի հեծնել", type: "phrase", baseVerb: "montar" },
  { id: "188", spanish: "montar un negocio", armenian: "բիզնես հիմնել", type: "phrase", baseVerb: "montar" },
  { id: "189", spanish: "mostrar / enseñar", armenian: "ցույց տալ", type: "ar", baseVerb: "mostrar" },
  { id: "190", spanish: "morir / morirse", armenian: "մահանալ", type: "reflexive", baseVerb: "morirse" },
  { id: "191", spanish: "no tener ni idea", armenian: "գաղափար չունենալ", type: "phrase", baseVerb: "tener" },
  { id: "192", spanish: "nadar", armenian: "լողալ", type: "ar", baseVerb: "nadar" },
  { id: "193", spanish: "no gustar nada", armenian: "ընդհանրապես դուր չգալ", type: "phrase", baseVerb: "gustar" },
  { id: "194", spanish: "nevar", armenian: "ձյուն գալ", type: "ar", baseVerb: "nevar" },
  { id: "195", spanish: "limpiar", armenian: "մաքրել", type: "ar", baseVerb: "limpiar" },
  { id: "196", spanish: "obtener", armenian: "ստանալ", type: "er", baseVerb: "obtener" },
  { id: "197", spanish: "ocupar", armenian: "զբաղեցնել", type: "ar", baseVerb: "ocupar" },
  { id: "198", spanish: "regalar", armenian: "նվիրել", type: "ar", baseVerb: "regalar" },
  { id: "199", spanish: "ofrecer", armenian: "առաջարկել", type: "er", baseVerb: "ofrecer" },
  { id: "200", spanish: "organizar", armenian: "կազմակերպել", type: "ar", baseVerb: "organizar" },
  { id: "201", spanish: "atreverse a", armenian: "համարձակվել", type: "reflexive", baseVerb: "atreverse" },
  { id: "202", spanish: "olvidar", armenian: "մոռանալ", type: "ar", baseVerb: "olvidar" },
  { id: "203", spanish: "abrir", armenian: "բացել", type: "ir", baseVerb: "abrir" },
  { id: "204", spanish: "perdonar", armenian: "ներել", type: "ar", baseVerb: "perdonar" },
  { id: "205", spanish: "hablar", armenian: "խոսել", type: "ar", baseVerb: "hablar" },
  { id: "206", spanish: "compartir", armenian: "կիսվել", type: "ir", baseVerb: "compartir" },
  { id: "207", spanish: "irse", armenian: "հեռանալ / գնալ", type: "reflexive", baseVerb: "irse" },
  { id: "208", spanish: "salir", armenian: "դուրս գալ", type: "ir", baseVerb: "salir" },
  { id: "209", spanish: "pasar", armenian: "անցնել / անցկացնել", type: "ar", baseVerb: "pasar" },
  { id: "210", spanish: "pagar", armenian: "վճարել", type: "ar", baseVerb: "pagar" },
  { id: "211", spanish: "pensar en", armenian: "մտածել", type: "phrase", baseVerb: "pensar" },
  { id: "212", spanish: "perder", armenian: "կորցնել / բաց թողնել", type: "er", baseVerb: "perder" },
  { id: "213", spanish: "planificar", armenian: "պլանավորել", type: "ar", baseVerb: "planificar" },
  { id: "214", spanish: "llorar", armenian: "լացել", type: "ar", baseVerb: "llorar" },
  { id: "215", spanish: "llover", armenian: "անձրև գալ", type: "er", baseVerb: "llover" },
  { id: "216", spanish: "hacer una pregunta", armenian: "հարց տալ", type: "phrase", baseVerb: "hacer" },
  { id: "217", spanish: "poder", armenian: "կարողանալ", type: "er", baseVerb: "poder" },
  { id: "218", spanish: "practicar", armenian: "զբաղվել / պարապել", type: "ar", baseVerb: "practicar" },
  { id: "219", spanish: "preferir", armenian: "նախընտրել", type: "ir", baseVerb: "preferir" },
  { id: "220", spanish: "tomar", armenian: "վերցնել / խմել / ընդունել", type: "ar", baseVerb: "tomar" },
  { id: "221", spanish: "coger", armenian: "վերցնել", type: "er", baseVerb: "coger" },
  { id: "222", spanish: "despedirse de alguien", armenian: "հրաժեշտ տալ ինչ-որ մեկին", type: "phrase", baseVerb: "despedirse" },
  { id: "223", spanish: "desayunar", armenian: "նախաճաշել", type: "ar", baseVerb: "desayunar" },
  { id: "224", spanish: "tomar algo", armenian: "ինչ-որ բան խմել / ուտել", type: "phrase", baseVerb: "tomar" },
  { id: "225", spanish: "preparar", armenian: "պատրաստել", type: "ar", baseVerb: "preparar" },
  { id: "226", spanish: "presentar", armenian: "ներկայացնել", type: "ar", baseVerb: "presentar" },
  { id: "227", spanish: "avisar", armenian: "զգուշացնել / տեղեկացնել", type: "ar", baseVerb: "avisar" },
  { id: "228", spanish: "aprovechar", armenian: "օգտվել", type: "ar", baseVerb: "aprovechar" },
  { id: "229", spanish: "disfrutar de", armenian: "վայելել", type: "phrase", baseVerb: "disfrutar" },
  { id: "230", spanish: "proponer", armenian: "առաջարկել", type: "er", baseVerb: "proponer" },
  { id: "231", spanish: "contar", armenian: "պատմել / հաշվել", type: "ar", baseVerb: "contar" },
  { id: "232", spanish: "ordenar", armenian: "դասավորել", type: "ar", baseVerb: "ordenar" },
  { id: "233", spanish: "suspender un examen", armenian: "քննությունից կտրվել", type: "phrase", baseVerb: "suspender" },
  { id: "234", spanish: "recibir", armenian: "ստանալ", type: "ir", baseVerb: "recibir" },
  { id: "235", spanish: "investigar", armenian: "ուսումնասիրել / հետազոտել", type: "ar", baseVerb: "investigar" },
  { id: "236", spanish: "pensárselo", armenian: "մտածել որոշումից առաջ", type: "reflexive", baseVerb: "pensarse" },
  { id: "237", spanish: "mirar", armenian: "նայել", type: "ar", baseVerb: "mirar" },
  { id: "238", spanish: "ver la tele", armenian: "հեռուստացույց դիտել", type: "phrase", baseVerb: "ver" },
  { id: "239", spanish: "sentir", armenian: "զգալ / ափսոսալ", type: "ir", baseVerb: "sentir" },
  { id: "240", spanish: "volver a + infinitivo", armenian: "նորից անել", type: "phrase", baseVerb: "volver" },
  { id: "241", spanish: "hacer un favor", armenian: "լավություն անել", type: "phrase", baseVerb: "hacer" },
  { id: "242", spanish: "visitar a alguien", armenian: "այցելել ինչ-որ մեկին", type: "phrase", baseVerb: "visitar" },
  { id: "243", spanish: "regresar", armenian: "վերադառնալ", type: "ar", baseVerb: "regresar" },
  { id: "244", spanish: "planchar", armenian: "արդուկել", type: "ar", baseVerb: "planchar" },
  { id: "245", spanish: "repetir", armenian: "կրկնել", type: "ir", baseVerb: "repetir" },
  { id: "246", spanish: "contestar", armenian: "պատասխանել", type: "ar", baseVerb: "contestar" },
  { id: "247", spanish: "reservar", armenian: "ամրագրել", type: "ar", baseVerb: "reservar" },
  { id: "248", spanish: "quedarse", armenian: "մնալ", type: "reflexive", baseVerb: "quedarse" },
  { id: "249", spanish: "aprobar", armenian: "հանձնել / հաստատել", type: "ar", baseVerb: "aprobar" },
  { id: "250", spanish: "volver", armenian: "վերադառնալ", type: "er", baseVerb: "volver" },
  { id: "251", spanish: "soñar con", armenian: "երազել", type: "phrase", baseVerb: "soñar" },
  { id: "252", spanish: "reír", armenian: "ծիծաղել", type: "ir", baseVerb: "reír" },
  { id: "253", spanish: "dirigirse a", armenian: "դիմել", type: "reflexive", baseVerb: "dirigirse" },
  { id: "254", spanish: "pasárselo bien", armenian: "լավ ժամանակ անցկացնել", type: "phrase", baseVerb: "pasarse" },
  { id: "255", spanish: "divertirse", armenian: "զվարճանալ", type: "reflexive", baseVerb: "divertirse" },
  { id: "256", spanish: "llamarse", armenian: "կոչվել", type: "reflexive", baseVerb: "llamarse" },
  { id: "257", spanish: "acercarse a", armenian: "մոտենալ", type: "reflexive", baseVerb: "acercarse" },
  { id: "258", spanish: "sentarse", armenian: "նստել", type: "reflexive", baseVerb: "sentarse" },
  { id: "259", spanish: "dormirse", armenian: "քնել / քուն մտնել", type: "reflexive", baseVerb: "dormirse" },
  { id: "260", spanish: "aburrirse", armenian: "ձանձրանալ", type: "reflexive", baseVerb: "aburrirse" },
  { id: "261", spanish: "expresarse", armenian: "արտահայտվել", type: "reflexive", baseVerb: "expresarse" },
  { id: "262", spanish: "vestirse", armenian: "հագնվել", type: "reflexive", baseVerb: "vestirse" },
  { id: "263", spanish: "acostumbrarse a", armenian: "սովորել", type: "phrase", baseVerb: "acostumbrarse" },
  { id: "264", spanish: "matricularse", armenian: "գրանցվել ուսման համար", type: "reflexive", baseVerb: "matricularse" },
  { id: "265", spanish: "registrarse", armenian: "գրանցվել", type: "reflexive", baseVerb: "registrarse" },
  { id: "266", spanish: "atender a alguien", armenian: "սպասարկել / ուշադրություն դարձնել", type: "phrase", baseVerb: "atender" },
  { id: "267", spanish: "saludar", armenian: "ողջունել", type: "ar", baseVerb: "saludar" },
  { id: "268", spanish: "saber", armenian: "իմանալ / կարողանալ", type: "er", baseVerb: "saber" },
  { id: "269", spanish: "dedicarse a", armenian: "նվիրվել / զբաղվել", type: "phrase", baseVerb: "dedicarse" },
  { id: "270", spanish: "acostarse", armenian: "պառկել քնելու", type: "reflexive", baseVerb: "acostarse" },
  { id: "271", spanish: "disfrazarse de", armenian: "կերպարանափոխվել / զգեստավորվել", type: "phrase", baseVerb: "disfrazarse" },
  { id: "272", spanish: "darse prisa", armenian: "շտապել", type: "phrase", baseVerb: "darse" },
  { id: "273", spanish: "ducharse", armenian: "լոգանք ընդունել", type: "reflexive", baseVerb: "ducharse" },
  { id: "274", spanish: "enfadarse con", armenian: "բարկանալ ինչ-որ մեկի վրա", type: "phrase", baseVerb: "enfadarse" },
  { id: "275", spanish: "tomar el sol", armenian: "արևայրուք ընդունել", type: "phrase", baseVerb: "tomar" },
  { id: "276", spanish: "lanzarse", armenian: "նետվել / սկսել համարձակորեն", type: "reflexive", baseVerb: "lanzarse" },
  { id: "277", spanish: "levantarse", armenian: "վեր կենալ", type: "reflexive", baseVerb: "levantarse" },
  { id: "278", spanish: "alojarse", armenian: "մնալ / կացարան գտնել", type: "reflexive", baseVerb: "alojarse" },
  { id: "279", spanish: "mantenerse", armenian: "մնալ / պահպանվել", type: "reflexive", baseVerb: "mantenerse" },
  { id: "280", spanish: "no fiarse", armenian: "չվստահել", type: "phrase", baseVerb: "fiarse" },
  { id: "281", spanish: "relacionarse con", armenian: "հարաբերություն ունենալ / կապ հաստատել", type: "phrase", baseVerb: "relacionarse" },
  { id: "282", spanish: "pasear", armenian: "զբոսնել", type: "ar", baseVerb: "pasear" },
  { id: "283", spanish: "relajarse", armenian: "հանգստանալ", type: "reflexive", baseVerb: "relajarse" },
  { id: "284", spanish: "darse cuenta de", armenian: "հասկանալ / գիտակցել", type: "phrase", baseVerb: "darse" },
  { id: "285", spanish: "descansar", armenian: "հանգստանալ", type: "ar", baseVerb: "descansar" },
  { id: "286", spanish: "secarse", armenian: "չորանալ / չորացնել իրեն", type: "reflexive", baseVerb: "secarse" },
  { id: "287", spanish: "sentirse", armenian: "իրեն զգալ", type: "reflexive", baseVerb: "sentirse" },
  { id: "288", spanish: "acordarse de", armenian: "հիշել", type: "phrase", baseVerb: "acordarse" },
  { id: "289", spanish: "callarse", armenian: "լռել", type: "reflexive", baseVerb: "callarse" },
  { id: "290", spanish: "preocuparse", armenian: "անհանգստանալ", type: "reflexive", baseVerb: "preocuparse" },
  { id: "291", spanish: "equivocarse", armenian: "սխալվել", type: "reflexive", baseVerb: "equivocarse" },
  { id: "292", spanish: "servir para", armenian: "ծառայել ինչ-որ բանի համար", type: "phrase", baseVerb: "servir" },
  { id: "293", spanish: "localizar", armenian: "տեղորոշել", type: "ar", baseVerb: "localizar" },
  { id: "294", spanish: "esquiar", armenian: "դահուկ քշել", type: "ar", baseVerb: "esquiar" },
  { id: "295", spanish: "sacar", armenian: "հանել / դուրս բերել", type: "ar", baseVerb: "sacar" },
  { id: "296", spanish: "sacar la basura", armenian: "աղբը հանել", type: "phrase", baseVerb: "sacar" },
  { id: "297", spanish: "sacar al perro", armenian: "շանը դուրս տանել", type: "phrase", baseVerb: "sacar" },
  { id: "298", spanish: "desear", armenian: "ցանկանալ", type: "ar", baseVerb: "desear" },
  { id: "299", spanish: "soportar", armenian: "դիմանալ", type: "ar", baseVerb: "soportar" },
  { id: "300", spanish: "suponer", armenian: "ենթադրել", type: "er", baseVerb: "suponer" },
  { id: "301", spanish: "tardar en", armenian: "ուշանալ / ժամանակ պահանջել", type: "phrase", baseVerb: "tardar" },
  { id: "302", spanish: "bajar de Internet", armenian: "ներբեռնել ինտերնետից", type: "phrase", baseVerb: "bajar" },
  { id: "303", spanish: "llamar por teléfono", armenian: "հեռախոսով զանգել", type: "phrase", baseVerb: "llamar" },
  { id: "304", spanish: "caerse", armenian: "ընկնել", type: "reflexive", baseVerb: "caerse" },
  { id: "305", spanish: "enamorarse", armenian: "սիրահարվել", type: "reflexive", baseVerb: "enamorarse" },
  { id: "306", spanish: "tocar", armenian: "դիպչել / նվագել", type: "ar", baseVerb: "tocar" },
  { id: "307", spanish: "girar", armenian: "շրջվել / պտտվել", type: "ar", baseVerb: "girar" },
  { id: "308", spanish: "traducir", armenian: "թարգմանել", type: "ir", baseVerb: "traducir" },
  { id: "309", spanish: "trabajar", armenian: "աշխատել", type: "ar", baseVerb: "trabajar" },
  { id: "310", spanish: "encontrar", armenian: "գտնել", type: "ar", baseVerb: "encontrar" },
  { id: "311", spanish: "utilizar", armenian: "օգտագործել", type: "ar", baseVerb: "utilizar" },
  { id: "312", spanish: "valer", armenian: "արժենալ / արժեք ունենալ", type: "er", baseVerb: "valer" },
  { id: "313", spanish: "vender", armenian: "վաճառել", type: "er", baseVerb: "vender" },
  { id: "314", spanish: "venir", armenian: "գալ", type: "ir", baseVerb: "venir" },
  { id: "315", spanish: "acabar de + infinitivo", armenian: "հենց նոր անել", type: "phrase", baseVerb: "acabar" },
  { id: "316", spanish: "viajar", armenian: "ճանապարհորդել", type: "ar", baseVerb: "viajar" }
];
